FROM node:20-alpine

WORKDIR /app

ARG API_URL=http://qrgen-backend:5000

COPY Frontend/QRGen/QRGen-frontend/package*.json ./

RUN npm install

COPY Frontend/QRGen/QRGen-frontend/ ./

RUN VITE_API_URL=$API_URL npm run build

RUN npm install -g serve

EXPOSE 3000

CMD ["serve", "-s", "dist", "-l", "3000"]
